// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwB9TbcRw5wtFPCpBbbxPNKI902bzoX18',
    appId: '1:769863226610:web:68123e04dea9824638ec6b',
    messagingSenderId: '769863226610',
    projectId: 'baocao-32859',
    authDomain: 'baocao-32859.firebaseapp.com',
    // Bucket name phải là <project-id>.appspot.com, không phải domain firebasestorage.app
    storageBucket: 'baocao-32859.appspot.com',
    measurementId: 'G-D6GM2JDKC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vsausJqfLccTo98UVrbIWSpinRlcOZ4',
    appId: '1:769863226610:android:1fd4bce4edbb8fb438ec6b',
    messagingSenderId: '769863226610',
    projectId: 'baocao-32859',
    storageBucket: 'baocao-32859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3-soiMgqdB2phPxNRiTe3xHNxbXNtSGQ',
    appId: '1:769863226610:ios:11fb8cea87d184a938ec6b',
    messagingSenderId: '769863226610',
    projectId: 'baocao-32859',
    storageBucket: 'baocao-32859.appspot.com',
    iosBundleId: 'com.example.baocaocuoiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3-soiMgqdB2phPxNRiTe3xHNxbXNtSGQ',
    appId: '1:769863226610:ios:11fb8cea87d184a938ec6b',
    messagingSenderId: '769863226610',
    projectId: 'baocao-32859',
    storageBucket: 'baocao-32859.appspot.com',
    iosBundleId: 'com.example.baocaocuoiky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwB9TbcRw5wtFPCpBbbxPNKI902bzoX18',
    appId: '1:769863226610:web:9ed1ed229d6f5b6538ec6b',
    messagingSenderId: '769863226610',
    projectId: 'baocao-32859',
    authDomain: 'baocao-32859.firebaseapp.com',
    storageBucket: 'baocao-32859.appspot.com',
    measurementId: 'G-P6422BFT7F',
  );
}
